name: CI/CD Pipeline with Sustainability Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sustainability-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install Backend Dependencies
      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm install

      # Step 4: Start the Backend Server
      - name: Start Backend Server
        working-directory: ./server
        run: npm start &
        env:
          PORT: 3000
        # Allow server to initialize
      - name: Wait for Server Startup
        run: sleep 10

      # Step 5: Run Lighthouse Audits via the Backend
      - name: Run Lighthouse Audits
        working-directory: ./server
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"url": "https://example.com"}' \
          http://localhost:3000/api/lighthouse/run > lighthouse-result.json
        continue-on-error: true

      # Step 6: Validate Sustainability Metrics
      - name: Validate Sustainability Metrics
        run: |
          RESULT=$(cat ./server/lighthouse-result.json | jq '.audits')
          CO2=$(echo $RESULT | jq -r '.["co2-emission-audit"].details.items[0].emission')
          if (( $(echo "$CO2 > 1" | bc -l) )); then
            echo "CO2 emissions exceed the target of 1 gram per page load."
            exit 1
          fi
          echo "Sustainability metrics are within acceptable ranges."
        env:
          NODE_ENV: production
