# File: .github/workflows/sustainability-audit.yml
name: Sustainability Audit & Goal Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit-and-goal-check:
    runs-on: ubuntu-latest
    env:
      AUDIT_URL: ${{ secrets.AUDIT_URL }}       # e.g. https://my.production.site
      BACKEND_PORT: 3000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend (if needed)
        run: npm run build --if-present

      - name: Start Express backend
        run: |
          npm run start:server &            # your script to start Express on port 3000
          echo "Waiting for backend to be ready..."
          npx wait-on http://localhost:${{ env.BACKEND_PORT }}/api/lighthouse/run --timeout 60s

      - name: Run Lighthouse Goal Check
        # This will invoke check-goal.js, which exits 1 if the goal is not met
        run: |
          node check-goal.js \
            "${{ env.AUDIT_URL }}" \
            "http://localhost:${{ env.BACKEND_PORT }}/api/lighthouse/run" \
            "http://localhost:${{ env.BACKEND_PORT }}/api/goals"

      - name: Report success
        if: ${{ always() }}
        run: echo "Sustainability goal met! 🎉"
