# File: .github/workflows/sustainability-audit.yml
name: Sustainability Audit & Goal Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  audit-and-goal-check:
    runs-on: ubuntu-latest
    env:
      AUDIT_URL: ${{ secrets.AUDIT_URL }}
      BACKEND_PORT: 3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies (including sqlite & sqlite3)
        run: |
          npm ci
          npm install sqlite sqlite3 nodemon wait-on --save-dev

      - name: Build frontend (if present)
        run: npm run build --if-present

      - name: Start Express backend
        run: |
          npm run start:server &            # starts your Express app
          echo "Waiting 20s for server to be ready..."
          sleep 20                           # simple delay instead of wait-on

      - name: Run Sustainability Goal Check
        run: node server/check-goal.js "http://localhost:4200/#/lighthouse"

      - name: Report result
        if: ${{ always() }}
        run: echo "🔍 Sustainability check complete."
